# Site settings
title: Chris Callahan
email: chris@callahan.io
description: > # this means to ignore newlines until "baseurl:"
  Decoding coding. HTML, CSS, JavaScript. Computer Science. Other thoughts on programming.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://callahan.io" # the base hostname & protocol for your site
twitter_username: _c_cal
github_username:  callahanchris
permalink: /blog/:year/:month/:day/:title

# Build settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-redirect-from